### ISSUE TITLE
paper fig 2 and code implementation not same

### ISSUE THREAD

**Issue by trobitack** [rhymesg/SRNN#1]
When we look at fig 2 in paper, we see nodeRNN takes (spatial, temporal and nodedata), three different kind of data. At that point fig 2 says node data is node previous sequence length data. Let say we have 3 node. and at time 11 for node 2 for seq len 10; the input must be shape (10,1) w.r.t the fig 2. But in code we see model.py line 202 ''self.NodeRNN(data_nodes[dataIdx],h_edgeRNN,h_nodeRNN,c_nodeRNN)''
data_nodes[dataIdx] gives all node data for time t. In my example, data_nodes shape is (3,1) w.r.t in your code . I am right ?  . Why there is a difference with fig and code? thanks

**Comment by rhymesg** [comment]
Thank you for your comment.
I'm not sure if I understood your question precisely. But note that the NodeRNN block in Fig. 2 depicts the architecture regarding a single node 'u'. In the implementation, `NodeRNN` is taking input for all the nodes at the time step `dataIdx`, which is {x_u^t} for all u in V, and the model gives prediction for all nodes at once. So the shape of `data_nodes[dataIdx]` becomes `("number of nodes", 1)`. This process is repeated for each time step, say, t - l + 1, ..., t - 1, t as the standard RNNs do.
The time sequence data have been fed into the `EdgeRNN_temporal` and `h_edgeRNN` encapsulates the information.
